// 示例配置数组
const demoConfig = [
  {
    id: "360vr",
    title: "360Vr",
    description: "Three.js 360vr demo",
    thumbnail: "/src/demos/360vr/thumbnail.jpg",
    tags: ["demo"],
  },
  {
    id: "airplane",
    title: "沿着路线飞行",
    description: "Three.js airplane demo",
    thumbnail: "/src/demos/airplane/thumbnail.jpg",
    tags: ["demo"],
  },
  //   {
  //     id: "animate",
  //     title: "Animate",
  //     description: "Three.js animate demo",
  //     thumbnail: "/src/demos/animate/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "animated-line",
  //     title: "Animated Line",
  //     description: "Three.js animated line demo",
  //     thumbnail: "/src/demos/animated-line/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "ballnoise",
  //     title: "Ballnoise",
  //     description: "Three.js ballnoise demo",
  //     thumbnail: "/src/demos/ballnoise/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "biaobai",
  //     title: "Biaobai",
  //     description: "Three.js biaobai demo",
  //     thumbnail: "/src/demos/biaobai/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "cannon",
  //     title: "Cannon",
  //     description: "Three.js cannon demo",
  //     thumbnail: "/src/demos/cannon/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "car-color",
  //     title: "Car Color",
  //     description: "Three.js car color demo",
  //     thumbnail: "/src/demos/car-color/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "card",
  //     title: "Card",
  //     description: "Three.js card demo",
  //     thumbnail: "/src/demos/card/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "connect",
  //     title: "Connect",
  //     description: "Three.js connect demo",
  //     thumbnail: "/src/demos/connect/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "crystal-ball",
  //     title: "Crystal Ball",
  //     description: "Three.js crystal ball demo",
  //     thumbnail: "/src/demos/crystal-ball/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "cube",
  //     title: "Cube",
  //     description: "Three.js cube demo",
  //     thumbnail: "/src/demos/cube/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "cubeliu",
  //     title: "Cubeliu",
  //     description: "Three.js cubeliu demo",
  //     thumbnail: "/src/demos/cubeliu/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "demo",
  //     title: "Demo",
  //     description: "Three.js demo demo",
  //     thumbnail: "/src/demos/demo/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "demo2",
  //     title: "Demo2",
  //     description: "Three.js demo2 demo",
  //     thumbnail: "/src/demos/demo2/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "earth",
  //     title: "Earth",
  //     description: "Three.js earth demo",
  //     thumbnail: "/src/demos/earth/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "effect",
  //     title: "Effect",
  //     description: "Three.js effect demo",
  //     thumbnail: "/src/demos/effect/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "feitan",
  //     title: "Feitan",
  //     description: "Three.js feitan demo",
  //     thumbnail: "/src/demos/feitan/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "font",
  //     title: "Font",
  //     description: "Three.js font demo",
  //     thumbnail: "/src/demos/font/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "font-demo",
  //     title: "Font Demo",
  //     description: "Three.js font demo demo",
  //     thumbnail: "/src/demos/font-demo/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "geojson",
  //     title: "Geojson",
  //     description: "Three.js geojson demo",
  //     thumbnail: "/src/demos/geojson/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "geometry-points",
  //     title: "Geometry Points",
  //     description: "Three.js geometry points demo",
  //     thumbnail: "/src/demos/geometry-points/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "glslify",
  //     title: "Glslify",
  //     description: "Three.js glslify demo",
  //     thumbnail: "/src/demos/glslify/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "gltransition",
  //     title: "Gltransition",
  //     description: "Three.js gltransition demo",
  //     thumbnail: "/src/demos/gltransition/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "godray",
  //     title: "Godray",
  //     description: "Three.js godray demo",
  //     thumbnail: "/src/demos/godray/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "group",
  //     title: "Group",
  //     description: "Three.js group demo",
  //     thumbnail: "/src/demos/group/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "gsap",
  //     title: "Gsap",
  //     description: "Three.js gsap demo",
  //     thumbnail: "/src/demos/gsap/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "gui",
  //     title: "Gui",
  //     description: "Three.js gui demo",
  //     thumbnail: "/src/demos/gui/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "happy",
  //     title: "Happy",
  //     description: "Three.js happy demo",
  //     thumbnail: "/src/demos/happy/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "huiguang",
  //     title: "Huiguang",
  //     description: "Three.js huiguang demo",
  //     thumbnail: "/src/demos/huiguang/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "l7",
  //     title: "L7",
  //     description: "Three.js l7 demo",
  //     thumbnail: "/src/demos/l7/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "line",
  //     title: "Line",
  //     description: "Three.js line demo",
  //     thumbnail: "/src/demos/line/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "map",
  //     title: "Map",
  //     description: "Three.js map demo",
  //     thumbnail: "/src/demos/map/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "meshline",
  //     title: "Meshline",
  //     description: "Three.js meshline demo",
  //     thumbnail: "/src/demos/meshline/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "mohu",
  //     title: "Mohu",
  //     description: "Three.js mohu demo",
  //     thumbnail: "/src/demos/mohu/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "noise",
  //     title: "Noise",
  //     description: "Three.js noise demo",
  //     thumbnail: "/src/demos/noise/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "pbr",
  //     title: "Pbr",
  //     description: "Three.js pbr demo",
  //     thumbnail: "/src/demos/pbr/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "photo",
  //     title: "Photo",
  //     description: "Three.js photo demo",
  //     thumbnail: "/src/demos/photo/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "point",
  //     title: "Point",
  //     description: "Three.js point demo",
  //     thumbnail: "/src/demos/point/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "raycaster",
  //     title: "Raycaster",
  //     description: "Three.js raycaster demo",
  //     thumbnail: "/src/demos/raycaster/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "react-three-fiber",
  //     title: "React Three Fiber",
  //     description: "Three.js react three fiber demo",
  //     thumbnail: "/src/demos/react-three-fiber/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "reactbits",
  //     title: "Reactbits",
  //     description: "Three.js reactbits demo",
  //     thumbnail: "/src/demos/reactbits/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "revealeffect",
  //     title: "Revealeffect",
  //     description: "Three.js revealeffect demo",
  //     thumbnail: "/src/demos/revealeffect/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "select",
  //     title: "Select",
  //     description: "Three.js select demo",
  //     thumbnail: "/src/demos/select/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "shader",
  //     title: "Shader",
  //     description: "Three.js shader demo",
  //     thumbnail: "/src/demos/shader/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "shengdanshu",
  //     title: "Shengdanshu",
  //     description: "Three.js shengdanshu demo",
  //     thumbnail: "/src/demos/shengdanshu/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "sound",
  //     title: "Sound",
  //     description: "Three.js sound demo",
  //     thumbnail: "/src/demos/sound/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "text",
  //     title: "Text",
  //     description: "Three.js text demo",
  //     thumbnail: "/src/demos/text/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "text-animate",
  //     title: "Text Animate",
  //     description: "Three.js text animate demo",
  //     thumbnail: "/src/demos/text-animate/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "text-animate copy",
  //     title: "Text Animate Copy",
  //     description: "Three.js text animate copy demo",
  //     thumbnail: "/src/demos/text-animate copy/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "three-uniapp",
  //     title: "Three Uniapp",
  //     description: "Three.js three uniapp demo",
  //     thumbnail: "/src/demos/three-uniapp/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "threejs-react-demo",
  //     title: "Threejs React Demo",
  //     description: "Three.js threejs react demo demo",
  //     thumbnail: "/src/demos/threejs-react-demo/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "tres",
  //     title: "Tres",
  //     description: "Three.js tres demo",
  //     thumbnail: "/src/demos/tres/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "vite-threejs-demo",
  //     title: "Vite Threejs Demo",
  //     description: "Three.js vite threejs demo demo",
  //     thumbnail: "/src/demos/vite-threejs-demo/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "vue-demo",
  //     title: "Vue Demo",
  //     description: "Three.js vue demo demo",
  //     thumbnail: "/src/demos/vue-demo/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "vue-threejs-demo",
  //     title: "Vue Threejs Demo",
  //     description: "Three.js vue threejs demo demo",
  //     thumbnail: "/src/demos/vue-threejs-demo/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "wave",
  //     title: "Wave",
  //     description: "Three.js wave demo",
  //     thumbnail: "/src/demos/wave/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "yanhua",
  //     title: "Yanhua",
  //     description: "Three.js yanhua demo",
  //     thumbnail: "/src/demos/yanhua/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
  //   {
  //     id: "yinhe",
  //     title: "Yinhe",
  //     description: "Three.js yinhe demo",
  //     thumbnail: "/src/demos/yinhe/thumbnail.jpg",
  //     tags: ["demo"],
  //   },
];

export default demoConfig;
